---
title: "Question matrix for the scoping review and additional data."
---





### Question matrix

| Question                                                                                 | Answer?                                       | Key papers                                                  |
| ---------------------------------------------------------------------------------------- | --------------------------------------------- | ----------------------------------------------------------- |
| Does SMP alter TCR signaling?                                                            | Yes                                           | Das 2015, Saitakis 2017, F.S. Majedi 2020                   |
| Are thymocytes mechanosensitive?                                                         | Well established evidence                     | A. Upadhyaya (2017), X. Wu & Z. Ye (2025), F.S. Majedi 2020 |
| Does ECM remodeling alter selection?                                                     | Hypothesis                                    | X                                                           |
| What kind of mechanical changes occur in the thymic stroma during age-related involution | No relevant data obtained from direct search. |                                                             |



### Connection to the hybrid simulation:
| Module        | Key question                                                                 | Summarized answers                                                                                                    | Candidate equations                 | Evidence quality & Open gaps           |
| ------------- | ---------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------- | ----------------------------------- | -------------------------------------- |
| TCR kinetics  | (1) Is catch-bond behavior established in thymocytes or only mature T cells? | It is observed in both thymocytes and mature T-cells                                                                  | Two-pathway catch-slip model        | Moderate; Need thymocyte-specific data |
| TCR dynamics  | Does cytoskeletal forces/organization influence TCR dynamics?                | Yes, [(EM-3) Info about different aspects of TCR functioning that are or can be influenced by substrate mechanics.]((EM-3)%20Info%20about%20different%20aspects%20of%20TCR%20functioning%20that%20are%20or%20can%20be%20influenced%20by%20substrate%20mechanics.) |                                     | Good                                   |
| Cytoskeleton  | Does stiffness alter actin organization?                                     |                                                                                                                       | Relaxation ODE for priming          | Strong; Parameter values uncertain     |
| ECM mechanics | How does thymic stiffness change with involution?                            |                                                                                                                       | Hill function for transmitted force | Limited; Sparse direct measurements    |
| Selection     | Can mechanics alter selection thresholds?                                    |                                                                                                                       | Kinetic proofreading extension      | Emerging; Mostly hypothesis            |


### Data on different cell populations in the thymus and some of their roles.
- The thymus road to a T cell migration, selection, and atrophy: 
	- The immune cell compartment is predominantly formed by developing T lymphocytes, but also includes minor populations of dendritic cells (DCs), macrophages, monocytes, neutrophils, eosinophils, natural killer (NK) cells, innate-lymphoid cells (ILCs), and B cells.
	- The cortex is the most cellular dense region in the thymus, accounting for about 70-80% of them, and is the primary site of positive selection. This region, less dense than the cortex, contains mature T cells, epithelial cells, Hassall’s corpuscles, macrophages, dendritic cells, B cells, and other myeloid cells .
	- Approximately 10-15% of all thymocytes, predominantly single positive (SP) CD4+ or CD8+ are located in the medullary region.
	- $\gamma$ $\delta$ T cells constitute less than 0.5% of the total murine thymocyte population.
	- In the cortex, DP T cells interact with cTECs, DCs, and B cells as antigen presenting cells (APCs).
	- There, they (SP T cells) engage with DCs, mTECs, and plasmacytoid dendritic cells (pDCS) for further screening.
	- A small fraction of thymic SP CD4+ T cells (∼1%) expressing the high-affinity IL-2 receptor alpha (IL-2R$\alpha$) or CD25 and displaying strong affinity for self-peptides, as revealed in Nur77GFP transgenic reporter mice, are agonist-selected to become Tregs.
	- During its most productive phase, the mouse thymus generates around 50 million of DP thymocytes each day that undergo a series of selection processes. In total, it is estimated that only 3-5% of developing thymocytes become mature CD4 or CD8 single positive (SP) T cells and exit the thymus.
- Structure and function of the thymic microenvironment:
	- More than 99% of the cells in the young adult thymus are developing thymocytes;
	- Dendritic cells are efficient antigen presenting cells, but do not themselves produce tissue restricted antigens. Rather, mTECs supply self-antigens to dendritic cells for efficient cross-presentation to thymocytes
- Central tolerance is impaired in the middle-aged thymic environment:
	- Mature mTECs play an essential role in tolerance induction, as they collectively express ~90% of the proteome;
	- A given TRA (tissue restricted antigen) is expressed by only ~1%–3% of mTECs (Derbinski et al., 2005, 2008), creating a sparse mosaic of self-antigen display in the medulla;




### Data on development of TCR, co-receptors and how TCR-coreceptor signaling contributes to fate/selection outcomes:
- The thymus road to a T cell migration, selection, and atrophy: 
	- In the subcapsular zone, where DN3 cells reside, part of the subset undergoes $\beta$ -selection (99) where the strength of the TCR$\beta$ chain is tested in combination with a surrogate “pre-TCR” before the TCR$\alpha$ chain is created.
	- The $\alpha$ $\beta$ vs $\gamma$ $\delta$ lineage choice is currently debated between by two different models. Firstly, the classical model includes a pre-commitment selection where the lineage fate is determined before TCR rearrangement. Secondly, the alternative model emphasizes the TCR signal strength and NOTCH signaling, rather than TCR identity, to dictate $\alpha$ $\beta$ vs $\gamma$ $\delta$lineage fate, **with strong TCR signal favoring $\gamma$ $\delta$-skewing**.
	- SP thymocytes exhibiting high-affinity TCR:MHC-self peptide interactions, considered autoreactive, can be redirected to become regulatory T cells (Treg), invariant natural killer T cells (iNKT) or TCR$\alpha$$\beta$ + CD8$\alpha$$\alpha$+ intestinal intraepithelial lymphocytes (IELs), in a process known as agonist selection.
	- The BCL-2 family member BIM is required for apoptosis of autoreactive SP CD4+ and CD8+ thymocytes. Indeed TCR ligation upregulated Bim expression and promoted interaction of BIM with BCL-XL, inhibiting its survival function.
- A TCR mechanotransduction signaling loop induces negative selection in the thymus(J. Hong et.al, 2018): 
	- Importance of co-receptors (for a future version of the model): A shift in the negative-selection threshold has been observed in thymocytes OT1.CD8.4 thymocytes, in which the wild-type (WT) CD8 is replaced by a chimeric coreceptor consisting of the CD8 ectodomain fused with the CD4 cytoplasmic tail. wQ4H7 interaction with OT1.CD8.4 thymocytes at low forces changed from the slip bond to a catch bond, correlating with the negative-selection threshold shift that changes Q4H7 from a positive-to a negative-selection ligand.  
	- CD4 (and CD8.4) associates with Lck more (hence has a higher signaling capacity) than CD8 . Our data suggest that enhancing the signaling capacity of the TCR stabilized its ligand binding.
-  Mechanoimmunology of T-Cell Activation (X. Wu & Z. Ye, 2025):
	- Thymocytes distinguish between positive and negative selecting ligands through dynamic catch bonds, with negative selecting ligands forming collaborative TCR–pMHC–CD8 trimolecular catch bonds, while positive selecting ligands form short-lived TCR–pMHC and pMHC–CD8 bimolecular slip bonds.
	- Studies show that mutant versions of non-stimulatory pMHC ligands with agonist activity can form catch bonds with TCRs, but they do not significantly increase 3D affinity. Therefore, the presence or absence of catch bonds can regulate TCR signaling in the T cell membrane environment, independent of pMHC binding affinity.
	- CD8 molecules play an equally important role in T-cell antigen recognition. The binding of CD8 to the TCR–pMHC complex markedly improves the calcium signaling response triggered by the sequential forces frequently exerted by agonist pMHC on the TCR.
- Mechanobiology of T Cell Activation: To Catch a Bond (B. Liu et.al., 2023):
	- . Notably, the CD8 coreceptor contributed more significantly to the overall TCR:pMHC interaction for less potent antigens (Jiang et al. 2011, Kolawole et al. 2018)



### Data on different components of thymic ECM:
- <u>The thymus road to a T cell migration, selection, and atrophy</u>: 
	- Thymic stromal cells, including epithelial cells and fibroblasts, actively produce ECM components such as collagen. The main ECM components include: collagen I, collagen III (to a lesser extent), collagen IV, fibronectin, and laminins (148–150). Collagen I is predominantly found in the intracapsular and intraseptal fibers, while collagen IV, fibronectin, and laminin are defining the membranes in the capsula, septa, and perivascular spaces.




### Data on thymocyte/T-cell properties (size, migrational speed, etc.) and how SMP can regulate these and other non-selection functions/pathways:
Size
Migrational speed
Activation-related pathways and processes

- Mechanical regulation of T-cell functions:
	- Responding to the changing mechanical cues and the presence of abundant biochemical cues (e.g. chemokines), the T cell changes to a motile mode by adjusting its adhesiveness via modulating integrin functional states and remolding the actin cytoskeleton (Fig. 1B). **In many biophysical aspects, migration of matured T cells in peripheral tissues is similar to migration of immature thymocytes in the thymus**.
	- T-cell migration is rapid. Typically, its migration speed is 10–40 $\mu$m/min, 100 times faster than many tissue cells (e.g. fibroblast).
	- Once encountered a rare APC, the motile T cell quickly slows down from a migrating speed of >10 $\mu$m/min to <2 $\mu$m/min to form a stable contact with the APC (27, 33). This deceleration is triggered by the TCR interaction with antigen pMHC with helps from coreceptor, costimulatory (e.g. cytotoxic T-lymphocyte antigen 4 (CTLA-4)), and adhesion (e.g. LFA-1) molecules.
- Central tolerance is impaired in the middle-aged thymic environment:
	- After positive selection, thymocytes upregulate the chemokine receptors CCR7 and CCR4, which promote their accumulation in the medulla where the corresponding chemokine ligands are expressed (Ehrlich et al., 2009; Hu et al., 2015; Ueno et al., 2004).
	- Thymocyte residence is limited to about 5 days in the medulla;
	- We find that the velocity of CD4SP cells is significantly reduced in a middle-aged 12MO versus young 1MO thymic environment, regardless of thymocyte age. This reduced speed could limit the number of APCs thymocytes encounter in a middle-aged thymus, diminishing the efficiency of central tolerance. Future studies are needed to determine why thymocyte migration is slower in a 12MO thymus.
- Aging is accompanied by {T}-cell stiffening and reduced interstitial migration through dysfunctional nuclear organization (G.R. Plaza et.al., 2022):
	- The mechanical characterization by micropipette aspiration showed that the progressive increase in T-cell apparent stiffness and viscosity occurred in the four sampling populations, which implies a progressive reduction on cells’ ability to passively deform;
	- Indeed, our experimental results (Figure 2d,e) confirmed that the spontaneous migration of T cells decreases with age (p = 0.0007), and is negatively correlated with deformability parameters, with an average Spearman’s coefficient ρ = 0.62  0.08 and 0.54  0.12 (mean  standard deviation) for the correlation respectively with elastic modulus and apparent viscosity;
	- The average content of myosin and vimentin showed a negative correlation with aging for all T-cell populations;
	- In previous works, the expression of the integrins CD11a and CD49d was observed to increase with age for circulating CD8+ T cells in mice;
	- According to previous studies, impaired immunity with increasing age can be partially attributed to a relative decline in T-cell migration. Three aging-related changes plausibly play an important role on the reduction of cell migration: the growth of relative size of the nucleus, the associated stiffness increase and the reduction of myosin content.
- Mediation of T-cell activation by actin meshworks (Beemiller and Krummel, 2010):
	- T cells (TC) display various modes of motility depending on the adhesive properties of their microenvironment. To achieve high velocities, T cells create series of small, short-lived contacts with substrates. The pseudopod sequences are generated by cycles of actin polymerization followed by myosin generated contractility. When T cells encounter the adhesion promoting surface of an APC, such as a dendritic cell (DC), integrin ligation causes the T cells to spread more extensively, maximizing surface interactions between the cells. Cell body motion does not completely stop, though, and T cells continue to drift over the surface of the APC as they scan for their cognate pMHC.
- Mechanosensing in the immune response (A. Upadhyaya, 2017):
	- Experiments in which stimulatory ligands were presented to T cells on PA substrates of varying stiffness showed that stiffer surfaces (100–200 kPa) elicited greater cytokine production in mouse CD4+ T cells than softer ones [20]. Conversely, human CD4+ cells were more strongly stimulated on 100–200 kPa PDMS substrates than stiffer ones (2 MPa), suggesting a biphasic response pattern of stiffness sensitivity.
	- In all cases, myosin inhibition led to loss of sensitivity to substrate stiffness. However, these results must be viewed against the fact that T cells are significantly softer (∼1 kPa) and most models of force generation posit that cellular forces rapidly saturate at substrate stiffness values that are ∼5–10 × of the cell’s stiffness.
	- Using PA substrates, we showed that traction forces exerted by T cells exhibited sigmoidal behavior as a function of substrate stiffness [19], with the total exerted forces saturating on surfaces of ~5 kPa stiffness.
	- Jurkat cells showed distinct differences in the dynamics of signaling and cell morphology as a function of substrate stiffness [19]. On stiff PA substrates (∼5 kPa), phosphotyrosine (pY) signaling rapidly peaked at ∼3 min after stimulation and declined to baseline levels, with monotonic expansion of the cell edge. On soft substrates (<1 kPa), pY signaling remained sustained even at 15 min but at lower levels, with the cell edge undergoing repeated rounds of protrusions and retractions.
	- Alternate strategies that mimic APCs in vivo may be better in stimulating T cells. Exploiting this, the Kam group used PDMS microbeads to stimulate CD4+ and CD8+ T cells and observed a stronger proliferative response [94]. However, itis unclear whether the enhanced proliferative response was due to the nanoscale structure of the polymer or changes in substrate rigidity.
	- Huse and colleagues have shown that the killing responses of cytotoxic T lymphocytes (CTL) are mechanosensitive and enhanced by forces [97]. Upon formation of an immune synapse like structure, CTLs secrete pore-forming proteins called perforins to lyse the target cell. Altering the membrane tension of the target cells using pharmacological means or osmotic shock and showed that perforin-induced pore formation was strongly affected. Similarly, altering the membrane tension of the target cells by changing substrate stiffness again altered cell killing, with cells on stiffer substrates being more sensitivity to perforin-induced pore formation.
- Mechanoimmunology of T-Cell Activation (X. Wu & Z. Ye, 2025):
	- Using peptide hydrogel scaffolds coupled with binding ligands, they demonstrated that both softer gels (0.5–1.0kPa) and harder gels (3.0kPa) stimulated CAR-T cell proliferation more effectively [197].
- Role of Mechanotransduction and Tension in T Cell Function (J. Rossy, 2018):
	- Durotaxis is another way how mechanotransduction could potentially contribute to T cell functions. Typical targets of T cells, such as (a) cancer cells that can be softer than normal cells; (b) tumors, that are stiffer than normal tissue because of high collagen density and crosslinking, or (c) antigen-presenting cells (6) have specific stiffness properties.
	- T cells pull more on stiffer substrates than on softer one. CD4 T cells produce also more IL-2 on harder substrates up to 100 kPa, but the stiffness contribution to T cell activation is somehow lost beyond 100 kPa. More generally, every aspect of T cell activation is potentiated by stiffer surfaces up to 100 kPa.
- Biophysical Aspects of T Lymphocyte Activation at the Immune Synapse (C. Hivroz & K. Saitakis, 2017):
	- Lymphocytes, such as other cell types, display membrane undulations with amplitude of several tens of nanometer and frequency ranging between 0.2 and 30 Hz.
	- T lymphocytes, when activated by the TCR–CD3, spread rapidly (in 2–4 min) on the activating substrate or cell they interact with, they stabilize (for 15–20 min), and then retract. These phases are reminiscent of the phases observed when adherent cells spread on their substrate.
- T-cell mechanobiology: How molecular forces shape immune function (Zubia-Aranburu et.al, 2026):
	- T lymphocytes develop ILPs that physically push against the endothelial cell surface, suggesting that the role of these protrusions is to test the stiffness of endothelial cells in order to find “soft” areas to cross through.
	- T-cell spreading, proliferation, and IL-2 secretion exhibit a biphasic dependence on stiffness, with optimal responses at intermediate values (Wahl et al., 2019; Yuan et al., 2021). This behavior is TCR-specific: it occurs with anti-CD3 stimulation alone but is abolished when integrin engagement (intracellular adhesion molecule (ICAM)-1/LFA-1) is present, leading instead to a monotonic increase in spreading. Similarly, nonspecific adhesion with poly-L-lysine without anti-CD3 does not reproduce the biphasic response. These findings highlight that T-cell responses to stiffness are not simply linear but biphasic and context-dependent, governed by TCR signaling, integrin engagement, and cytoskeletal dynamics.
	- Recent work showed that T cells exposed to heterogeneous substrates with alternating soft and stiff regions do not average mechanical inputs but rather adopt a response characteristic of the soft regions, giving rise to lower activation with respect to cells on uniformly stiff surfaces (Pandit et al., 2025). This demonstrates that soft regions can dominate T-cell mechanosensing.
	- Under identical CD3/CD28 stimulation, slow-relaxing matrices promote the expression of both activation and inhibitory markers, whereas fast-relaxing matrices favor memory T-cell marker expression, demonstrating that the temporal dimension of mechanical feedback is a key determinant of the functional outcome (AduBerchie et al., 2023). In line with these observations, synthetic viscoelastic alginate-based beads with rapid stress relaxation dynamics (unlike the purely elastic polystyrene Dynabeads) were shown to enhance cytotoxic function, increasing expression of CD69 (an early activation marker), perforin, granzyme B, and interferon-γ, expanding the CD8+ population, and reducing the proportion of Tregs (Liu et al., 2024b).
	- Micro- and nanoscale geometries have been shown to play a crucial role in T-cell behavior, although isolating the specific contribution of geometry from stiffness and ligand density remains challenging. For example, PDMS microbeads with a modulus of 7.3 MPa functionalized with antiCD3 and anti-CD28 induced a greater T-cell proliferation than commercial polystyrene Dynabeads (GPa range) (Lambert et al., 2017), extending the proliferative phase for both CD4+ and mixed CD4+/CD8+ T-cell populations. Importantly, cells expanded using PDMS beads exhibited similar effector functionality to those expanded using Dynabeads. Similarly, electrospun fibrous meshes composed of PDMS:PCL and functionalized with antiCD3 and anti-CD28 were more effective at stimulating T-cell proliferation than pure PCL meshes or Dynabeads, while maintaining comparable functionality to Dynabeads (Dang et al., 2018). In these meshes, microscale fibers outperformed nanoscale fibers in promoting proliferation, though both fiber types supported higher expansion than PCL-only ones. Overall, while both stiffness and geometry of the activating surface can enhance T-cell proliferation, their precise and independent contributions and their impact on functional quality remain to be fully resolved.
	- PIEZO1, activated by membrane tension, drives Ca2+ influx and actin remodeling necessary for TCR signaling, and its activation can effectively substitute CD3/CD28 stimulation (Liu et al., 2018).
	- Experiments using microporous 3D scaffold matrices of tunable rigidity demonstrated that T cells can sense and respond to the stiffness of their environment, with stiffer matrices enhancing activation, proliferation, and migration speed (Majedi et al., 2020).
	- Simulating such interfaces in vitro, micrometer-scale topographies, such as pits of defined depth, modulate T-cell activation in a biphasic manner, with intermediate depths (∼4 μm) optimizing cytokine secretion and activation, whereas excessive confinement diminishes responses (Chaudhuri et al., 2020). At the nanoscale, confinement within 200-nm pores promotes the formation of actin-rich microvilli and spatial segregation of CD45 and TCRs, generating localized signaling hotspots that sustain activation even in the absence of TCR agonists (Aramesh et al., 2021).
	- Increased ECM stiffness enhances T-cell activation, inflammatory cytokine secretion, and integrin-mediated signaling, thereby reinforcing local immune activation and perpetuating tissue damage (Santos and Lagares, 2018). Moreover, Tregs show reduced suppressive capacity on stiff substrates and experience altered FOXP3 stability when subjected to mechanical load, shifting the balance toward effector responses (Shi et al., 2023).
- T-cell activation is modulated by the 3D mechanical microenvironment (F. S. Majedi et.al., 2020):
	- Experiments examining the interaction of T cells with stimulatory 2D surfaces of varying stiffnesses have demonstrated that relatively stiffer surfaces provide a stronger stimulus. Elastic moduli around 15–20 kPa enable maximal spreading of T cells and optimal activation. The cytotoxicity of T cells is also affected by substrate stiffness.
	- We found that the percentage of cells that expressed these cytokines (IL2, IFN-alpha and TNF-alpha) was higher in hard 3D scaffolds than those in softer scaffolds. Moreover, in examining the single-cell amount of cytokine expressed in these responsive cells, the T cells responding to antigen in the stiffer matrix produced more effector cytokines than those in a softer matrix.
	- This result shows that the enhanced activation of T cells encounter in stiff 3D scaffolds is independent of any mechanical effect of the APC.
	- We found that immune synapses of T cells formed in stiff matrices were significantly larger than those formed in soft matrices. There were no notable differences in the ultrastructural organization of actin and LFA-1 in the region of the IS in comparing T cells encountering APCs in stiff and soft matrices.
	- Across many experimental modalities, the finding has been consistent: within the physiological range, the stiffer the anchoring, the greater the T-cell activation. Our work here is distinguished from these prior papers because our T cells were activated by antigen borne on antigen presenting cells rather than by antigen anchored directly to the stiff or soft substrate. These data could support the notion that the APC may convey some microenvironmental information to T cells.
- Engineering an Artificial T‐Cell Stimulating Matrix for Immunotherapy (J.W. Hickey et.al, 2019):
	- A softer aTM (0.5 kPa) stimulated CD8+ T cell proliferation more effectively than the stiffer aTM (3 kPa) as determined by the dilution of the proliferation dye, carboxyfluorescein succinimidyl ester (CFSE). aTMs with a stiffness below 1 kPa were more effective at stimulating CD8+ T cell expansion, where we observed a dramatic decrease in T cell expansion occurs with aTM greater than 1 kPa. The gross morphological comparison between the two gels showed that the 0.5 kPa gels were more porous than the 3 kPa gels.
	- We added a blebbistatin, a myosin II inhibitor important in the role of T cell mechanotransduction, to the culture of a 0.5 kPa aTM. In the presence of the inhibitor, CD8+ T cell expansion is abolished even with the same amount of stimulatory ligand present.
	- Even providing cell-adhesive ligands did not help stiff aTMs (3 kPa) stimulate antigen-specific PMEL CD8+ T cells, whereas RGD further increased T cell proliferation on soft (0.5 kPa) aTM surfaces resulting in effective expansion.
	- This enhanced mechanotransduction at lower stiffness could be due to a number of reasons. First, softer hydrogels which are more compliant and may enable enhanced clustering of neighboring attached Signal 1 molecules on the hydrogel— shown to promote superior TCR signaling, which we observe in Figure 2H,I. Second, traditionally T cells are stimulated by surfaces which have stimulatory signals nonspecifically adsorbed to surfaces, whereas our signals are chemically attached to the matrix, which may contribute to more effective mechanotransduction. Third, the stiffness range of the aTM more closely matches the stiffness of the secondary lymphoid tissue. To our knowledge this represents the lowest stiffness of a surface, orders of magnitude less than T cells have been stimulated with, where traditionally the surface is a stiff (≈MPa) plastic. At softer hydrogel surfaces, we are approaching the appropriate level of resistance that a T cell may observe at a cellular level, where researchers have shown that the minimum adhesion strength to antigen presenting cells to be around 90 Pa. In conclusion the stiffness of the aTM is critical to enhance mechanotransduction TCR signaling for effective T cell expansion.
- T cell antigen receptor activation and actin cytoskeleton remodeling (S. Kumari et.al., 2013):
	- Lateral forces applied to TCR using non-stimulatory anti-CD3 monoclonal antibody were able to trigger cytoplasmic Ca2+ elevation and axial forces applied by micromanipulation were able to rescue T cell stimulating defects associated with elongated pMHC.
	- Mouse CD4+ T cells produced more IL-2 in response to polyacrylamide gels of increasing elastic modulus coated with anti-CD3 and anti-CD28 antibodies. Blebbistatin abolished the observed rigidity effect, which suggests that actomyosin cytoskeleton is involved in the T cell response to environmental mechanical rigidity. In the same study it was also shown that the mechanosensing response to the stiff substrate was mediated by the CD3 epsilon chain rather than CD28, under the conditions used; the involvement of the TCR, rather than CD28, had also been suggested by Li et al.. Consistent with the detection of increased level of IL-2 secretion in cells cultured on stiffer surfaces, clusters of phophorylated ZAP70 (pZAP70), phosphorylated Src family kinase proteins (Lck and Fyn) and phosphorylated proline rich tyrosine kinase-2 (pPYK2) were detected in the cell surface of these cells, whereas no (pZAP70 and pSFK) or only minor clusters (pPYK2) were observed in the cell surface of cells cultured on softer surfaces. Interestingly, under stiffer surfaces conditions, blebbistatin treatment did not alter the localization of pZAP70 and pSFK but had an effect on pPYK2 distribution, suggesting that PYK2 responds to cell contractility and contributes to the T cell mechanosensing mechanism. **It has been noted that correlations between cellular responses and substrate elastic modulus do not demonstrate a mechanical response, but may also be related to the chemistry of ligand presentation, which can also vary with gel and elastomer properties that alter elastic modulus.**
- Different TCR-induced T lymphocyte responses are potentiated by stiffness with variable sensitivity (M. Saitakis et.al, 2017):
	- Human T cells are extremely soft, in the range of 0.1 kPa (Bufi et al., 2015; Guillou et al., 2016), skeletal muscle stiffness is in the range of tens of kPa (Uffmann et al., 2004), while calcified bone can reach values of GPa (Gasiorowski et al., 2013). For many cell types, stiffness has been shown to influence cell growth, differentiation, migration and survival (Pelham and Wang, 1997; Lo et al., 2000; Discher et al., 2005; Engler et al., 2006; Solon et al., 2007; Oakes et al., 2009; Trappmann et al., 2012). In T cells, substrate stiffness was shown to affect T cell activation (Judokusumo et al., 2012; O’Connor et al., 2012; Tabdanov et al., 2015) and to regulate the forces exerted by T cells on their substrates (Husson et al., 2011; Hui et al., 2015).
	- Cytokines (TNF, IFNG, LTA, IL22, IL17A), T cell surface markers (BTLA, IL4R, CD40LG, IL2RA, CD69, ICOS), T-cell-specific transcription factors (TBX21 and FOXP3) and the proliferation transcription factor MYC all showed enhanced gene expression with increasing stiffness in the presence of aCD3.
	- Most prominently up-regulated pathways (GSEA using GO-BP and KEGG databases): For 0.5 kPa- T-cell activation and differentiation, 6.4 kPa- Apoptotic and survival signaling (mainly due to CUL2, SART1, BRCC3 and ERCC8 genes. Also T-cell viability was similar in all three substrates) & 100 kPa- respiratory electron transport and translation-related pathways.  
	- The majority of the genes showed an expression that was more increased from 0.5 kPa to 6.4 kPa (right of the diagonal) than from 6.4 kPa to 100 kPa (left of the diagonal) (Figure 3D). These genes included cytokines and related genes: IL22, IFNG, TNF, LTA, CD40LG, IL2RA, IRF4; transcription factors: FOXP3, TBX21, MYC; and metabolism-related genes: LDHA, ATP8B4. Many genes showed expression that continued to rise for both transitions (genes close to the diagonal), such as IL4R, CD69, NFKBIB, ENO1, PGK1, LMNA, and LMNB1. Other less numerous genes showed increased expression for the 6.4 to 100 kPa transition (IL23R, KIF21A, UBE2M, TNFRSF4).
	- CD4+ T lymphoblasts were cultured on PA-gels of varying stiffness coated with ICAM-1 and soluble aCD3+aCD28 were added. In these conditions, IFNg production was not affected by gel stiffness (Figure 4—figure supplement 1B) showing that mechanosensing indeed requires direct engagement of the TCR/CD3 complex with ligands on substrates of varying stiffness. 
	- Moreover, in the absence of ICAM-1 (PA-gels coated solely with biotinylated aCD3+aCD28), production of cytokines still followed substrate stiffness (Figure 4—figure supplement 1C) showing that ICAM-1 is not essential for the stiffness-mediated modulation of cytokine production.
	- T cells dramatically change their metabolic activity, switching from a metabolically quiescent state to aerobic glycolysis upon TCR triggering and co-stimulatory activation (Pearce et al., 2013). This T cell glycolytic switch induced by TCR triggering was increased by high stiffness values (100 kPa) but not by low ones (hundreds to thousands of Pa).
	- Changes in T cell metabolism are required to fuel proliferation induced upon T cell activation. Transcriptomic analysis indicated that TCR/CD3-induced mitotic cell cycle was sensitive to PA-gel stiffness, that is expression of cell-cycle-related genes, gene sets and pathways was potentiated in T cells activated by aCD3 on substrates of increasing stiffness. Moreover, nucleotide synthesis related genes were also increased by stiffness.
	- Results revealed that, at 24 hr, cell cycle progression, that is fewer cells in G0/G1 phases and significantly more cells in S phase and G2/M phases, was only evident for T cells activated by aCD3 on the high end of the stiffness range (100 kPa).
	- These results also show that T cell response to stiffness builds on with time, resulting eventually in a potentiation of T cell proliferation within the whole stiffness range tested.
	- Scanning electron microscopy images of T cells interacting with substrates from 0.5 to 100 kPa reveal that, in contrast to glass substrates, T cells do not spread evenly but rather form small protrusions, which tend to spread more on stiffer substrates (Figure 1D). This is consistent with in vitro studies showing that T cells probe their environment through close contacts over small areas (around 0.2 mm 2 ) (Brodovitch et al., 2015).
- Effect of binary mechanical environment on T-cell function (J.J. Pandit et.al., 2025):
	- The overall expression of CD107a by CD4+ T cells, as anticipated, is substantially lower than that by CD8+ T cells. Nevertheless, both subsets demonstrate the same pattens of CD107a expression consistent for all the donors, by which stiff control samples produced the highest degranulation. In contrast to stiff surfaces, both stiffness pattern and soft control produced similarly lower levels of degranulation, for both CD4+ T cells and CD8+ T cells, consistently for all the tested donors.
	- The effect of stiff surface on the expression CD69 was less pronounced than in the case of CD107a. On the other hand, stiffness pattern produced the same CD69 level as the soft control, mirroring the results of the CD107a expression. The lower sensitivity of CD69 than CD107a can be attributed to the difference in times at which these markers were probed.
	- It can be concluded that the type of surface insignificantly affected the general T cell proliferation. In all cases, a 15 to 40-fold expansion was achieved after 7 days, with no clear dependence on the activating conditions.
	- Previous studies were demonstrated that the stiffness of activating surface determines the proliferation of T cells, depending on the stiffness range. For the stiffnesses much above the physiological range, the proliferation was reported to increase with the decrease in the stiffness. Yet, for the stiffnesses of the physiological range, response of T cells to the stiffness variation is biphasic: it increases with the stiffness up to a peak of a few tens KPa (which corresponds to the stiffness of antigen presenting cells), and then decreases. In contrast, PDMS elasticity used in this research was about 100 kPa – which is above the optimal elasticity for T cell activation, and this can explain relatively lower proliferation it produced on day four.
- Microdevice for confinement of T-cells on functionalized bio-interfaces (C. Trenzinger et.al., 2025):
	- Cells seeded onto the activating bilayer spread out after seeding and showed significantly higher mean sectional cell areas even before confinement compared to the non-activating bilayer; however, their mean sectional cell areas did not change considerably upon confinement to 6 μm, despite individual cells showing increased values.
	- With the help of our developed microdevice we could show that T-cell outer dimensions and T-cell nuclei sizes are affected not only by confinement but also by SLB composition. With increasing antigen density, T-cells continue to spread out onto the flat SLB, which could be quantified by measuring an increase in their sectional cell and sectional nucleus areas. Similarly, confinement of T-cells to 6 μm increases these metrics. Notably, at the same confinement height, activated T-cells showed increased areas compared to resting T-cells. This observation implies that cellular and nuclear volume are increased upon T-cell activation.
	- Using micropipette aspiration techniques, Waugh et al. measured an ∼3-fold increase in T-cell volume upon activation, which aligns well with our sectional cell area data comparing resting with activating conditions. This increase in cellular volume is driven by ion channel activity, osmotic shifts, cytoskeletal remodelling and metabolic upregulation. Indeed, cell volume regulation was found to be essential for optimal T-cell function with volume-regulated anion channels (VRACs) playing a critical role in T-cell activation. Xu et al. identified a decompaction of chromatin in association with a disruption of the nuclear envelope during T lymphocyte activation. This was coupled with an overall increased nucleus size, which is in line with our findings of increased sectional nucleus areas in activated T-cells.
- Adhesion to laminin-1 and collagen-IV induces the formation of Ca2+ microdomains that sensitize mouse T-cells for activation (Mariella Weiß et.al., 2023):
	- In Jurkat T cells, integrin-mediated adhesion to ECM proteins triggers an increase in global free cytosolic calcium (Ca2+) concentration ([Ca2+]i) . Upon binding of integrins to ECM proteins, phosphorylation of focal adhesion kinase (FAK) and subsequent activation of phospholipase C–γ (PLC-γ) occurs. Thus, FAK is thought to be a key component of integrin-mediated signaling pathway. Moreover, Src family tyrosine kinases, the second messengers D-myo-inositol 1,4,5-trisphosphate (IP3) and cyclic adenosine 5′-diphosphoribose (cADPR), and store-operated calcium entry (SOCE) are components of α6β1-integrin–mediated global Ca2+ signaling.
- Nanoconfinement of microvilli alters gene expression and boosts T cell activation (M. Aramesh et.al., 2021):
	- Formation of high membrane curvature is thought to be sensed by triggering biological processes, such as the assembly of signaling micro-clusters. Formation of high membrane curvatures (200 to 1,000 nm in diameter) supports antigen recognition in T cells, through amplified and sustained signaling at the tip of the protrusions. Beside chemical signals, the physical environment of the cell can also regulate microvilli formation, particularly at the nanoscale.
	- Primary human T cells and Jurkat T cells exhibited a significant increase in expression of the membrane protein CD69 as well as secretion of IL-2 after 24 h of culture on porous compared to nonporous surfaces. Strikingly, up to 20% of the primary human cells exhibited a significant increase in CD69 expression after 24 h, and ∼10% of the cells expressed CD25 and proliferated after 4 d in conditions promoting formation of microvilli, and remarkably, this is happening in the absence of any TCR agonistic triggers.
	- Interestingly, the expression of CD69 and IL-2 secretion by T cells was only enhanced on the porous surface with 200-nm pore size without TCR agonistic antibodies. Moreover, we plotted CD69 expression versus the surface area of the porous membrane, which clearly indicates that there is no correlation between the up-regulation of activation markers and the surface area. For example, AAO with 400-nm pores has a four times larger surface area compared to AAO with 200-nm pores (200b nm versus 400b nm in Table 1), but CD69 and IL-2 were not up-regulated on the 400-nm substrates.
	- The expression of the target genes (such as _CD69, NFKB1, TCRA, PTPRC, and ITGAL_) was calculated relative to the expression of the genes on the nonporous surface as control. qPCR analysis revealed that the target genes were significantly up-regulated on 200-nm pores, but not on 400-nm pores. To verify the results, we tested the protein expression of TCR and CD45 at different time points (30 min to 24 h), which indicated that cells cultured on 200-nm pores exhibited higher expression of TCR and CD45.
	- The influence of actin polymerization inhibition on CD69 expression was much more significant on 200-nm pores compared to the other substrates, indicating that the enhanced activation on 200-nm pores is due to microvilli protrusions.
- Cytoskeletal forces during signaling activation in {Jurkat} {T}-cells (Hui et.al., 2014):
  - We found that cells were more dynamic, with cell edges displaying extensive protrusions and retractions and cell shape remodeling on soft gels. On stiff gels, cells typically spread out smoothly, with the cell edge advancing in a more isotropic manner. Furthermore, cell edge dynamics continued for a much longer period of time on softer gels, whereas on stiffer gels, cell edges either remained stably spread with minimal edge dynamics or retracted.
- Biphasic mechanosensitivity of {T} cell receptor-mediated spreading of lymphocytes (A. Wahl et.al., 2018):
	- Cells spread more on 20-kPa than on 2,440- kPa elastomers but the actin is peripherally distributed in both cases.
	- Cells on the softest elastomer (0.5 kPa) spread moderately (area about 200 µm2 ). The area increases as the stiffness is increased up to 5 kPa, reaching a maximum of about 300 µm2 . Thereafter the cell spread area decreases with increasing stiffness, falling back to roughly 200 µm2 for 2 MPa and to less than 150 µm2 at 7 MPa. On equivalently functionalized glass, with nonspecific interactions fully blocked, the cells spread to a mere 120 µm2 . The above experiments indicate that this unusual dependence of the spreading on elasticity is a specific TCR complex–mediated response and that both human T cell lines and primary human cells show this behavior.
	- Co-stimulation elicited no further spreading beyond that already observed for anti-CD3 alone, and the dependence on stiffness also remained unaffected, confirming the absence of a role for CD28 in TCR-mediated mechanosensing.
	- For the case of co-functionalization with both antiCD3 and ICAM-1, the cells spread the least on the softest substrates used and they spread more as the substrate stiffness is increased, already reaching a saturation value of about 400 µm2 in the kilopascal range. Thus, the maximal area reached here is larger than that with antiCD3 alone. The spreading dynamics do not differ between the soft (5 kPa) and hard (2,440 kPa) cases.
	- The spreading behavior is strikingly reproduced in human CD4+ naive T cells isolated from peripheral blood, which fail to spread on anti–CD3-functionalized hard PDMS without ICAM-1 but do spread on hard PDMS dually functionalized with ICAM-1 and anti-CD3, as well as on anti– CD3-coated soft PDMS with or without ICAM-1.
	- Treatment of cells on anti–CD3-coated substrates with blebbistatin has no effect on spreading and its stiffness dependence. Suppression of actin polymerization (using cytochalasin D) or of ARP-2/3–mediated branching (using CK666), however, completely prevents spreading on both hard and soft elastomers.
	- We could speculate that as seen both by Oakes et al. (36) and by us, mechanosensing associated with early spreading may be actin polymerization driven and perhaps nonmonotonic with substrate stiffness. Theoretically, while early work linked friction force generated by polymerization with kinetics of force-insensitive bonds.
- Biphasic response of {T} cell activation to substrate stiffness (D. J. Yuan et.al., 2021):
	- Across all activating substrates, T cells showed an initial period of increasing cell volume (rapid expansion that plateaued around 9–13 days as cells came to rest. However, the duration of this period of rapid growth and the peak number of cells generated from identical starting populations was sensitive to substrate stiffness; cells activated on 25 kPa gels showed the greatest fold increase in cell number, which within each experiment was associated with the longest period of expansion. These measures of cell expansion decreased as substrate stiffness either increased (towards 110 kPa) or decreased (towards 5 kPa).
	- IL-2 secretion is a hallmark of early T cell activation, and we observe the 25 kPa gel induces the highest secretion compared to the 5 kPa and 110 kPa (Fig. 3B), across both CD4+ and CD8+ populations.
	- At a concentration of 10 μM, blebbistatin abrogated the mechanosensing response; IL-2 secretion was similar across all hydrogel substrates, but higher than the non-stimulated control.
	- At 0.1 μM of latrunculin B, we observed a shift in IL-2 secretion pattern from a biphasic response shown by the vehicle control to a monotonic increase in activation with increasing stiffness. At 1 μM, we see a complete loss of activation across all conditions.
- Substrate rigidity regulates human {T} cell activation and proliferation (R. S. O'Connor et.al., 2012): 
	- Initial evaluation of T cell activation demonstrated that softer PDMS stimulatory substrate increased IL-2 secretion.
	- Using a CFSE dilution assay, greater proliferation was reproducibly observed at 72 h on softer surfaces. The difference in proliferation became more pronounced as the coating concentration of the goat anti-mouse capture Ab decreased ,1 mg/ml, with the proliferation completely lost on harder surfaces coated with Abs at low concentration (0.1 mg/ml).
	- The enhanced IL-2 secretion by T cells stimulated on softer substrates is primarily due to enhanced transcription at the IL-2 gene rather than a difference in the posttranscriptional regulation of IL-2 mRNA stability.
- Mechanosensing in T-lymphocyte activation (E. Judokusumo et.al., 2012):
	- IL-2 secretion was lowest on the softest (E ¼ 10 kPa) gels, and increased with substrate rigidity. A small, not statistically significant decrease was observed on the 200 kPa vs. 100 kPa gel, possibly reflecting lower T cell accessibility to the antibodies due to smaller gel pore size. Cell attachment also responds to substrate rigidity, with a lower density of cells observed on the softest surface compared to the three stiffer preparations.
	- Much larger increases in cell seeding density resulted in a minor statistically significant increase IL-2 secretion, but this was associated with a much larger increase in attachment density. Cooperativity between cells thus has an effect on cell activation that is small compared to mechanosensing.
	- Treatment of cells with blebbistatin (100 mM, Fig. 1 B) abrogated the sensitivity of IL-2 secretion across the three stiffest gels, indicating a role of cytoskeletal contractility in cell response.
	- These results suggest that T cell mechanosensing is associated with CD3 rather than CD28.
	- 






### Miscellaneous (possibly) important information:
- Mechanical regulation of T-cell functions:
	- Large and bulky molecules such as phosphatase CD45 are squeezed out to a distal region (dSMAC) outside the pSMAC (peripheral supramolecular activation cluster, formed at the immunological synapse). 
	- The force where catch-slip transition occurs defines an optimal force. Under such force, the molecular interaction becomes most stable in a range of forces. It may also provide a mechanism for the cell to select for or adapt to a mechanical microenvironment most suitable for its survival, proliferation, differentiation, and carrying out its functions.
	- Tolar and colleagues (151) demonstrated that B cells use mechanical energy to discriminate antigen.
- Central tolerance is impaired in the middle-aged thymic environment:
	- Notably, expression of TRAs in the medulla diminishes with age (Griffith et al., 2012), and thymic B cells and DCs change in composition and molecular properties;
	- "these data indicate that negative selection is impaired in the middle-aged thymus for CD8SPs responding to TRAs of lower TCR-binding avidities, due to either lower expression levels or reduced TCR-binding affinities."
	- CCL21, the CCR7 ligand responsible for attracting thymocytes into the medulla (Kozai et al., 2017), is expressed at higher levels in the medulla of middle-aged relative to young thymuses. Thus, our data indicate that impaired central tolerance in the middle-aged thymus is not due to reduced thymocyte medullary accumulation.
	- These findings show that the middle-aged thymic environment becomes less efficient at displaying ubiquitous self-antigens to induce negative selection, **effectively raising the avidity threshold for negative selection by middle-age**. The mechanisms underlying the deficit remain to be determined, but could reflect changes in APC composition, such as the reduced frequency of MHCIIhi cDCs.
- Human progenitor T-cell differentiation regulated by the mechanical resistance of thymus-mimetic extracellular matrices (N. Jeffreys et.al., 2025 | preprint) :
	- Actomyosin has extensive lateral contacts with the adherent substrate across the cell membrane through integrin-substrate coupling, and is postulated to enable receptor-mediated endocytosis and myosin-dependent tension to support the tensile load-dependent proteolytic activation of the notch1 pathway. Additionally, the presence of actomyosin at the nuclear periphery and its co-localization with the linker of Nucleoskeleton and Cytoskeleton (LINC) complex protein Nesprin2 and apical actin caps suggests that actomyosin contraction may support the nucleocytoplasmic transport of NICD and other macromolecular cargoes important in sustaining the T-cell development GRN (gene regulatory networks) by increasing nuclear influx through deformation of the nuclear pore complex (NPC).
- A TCR mechanotransduction signaling loop induces negative selection in the thymus (J. Hong et.al, 2018: 
	- When we plotted the survival frequency of CD8+ single-positive (SP) thymocytes previously reported in FTOC assays4 against the bond lifetime measured at zero force using the thermal fluctuation assay24, we found that, for the same panel of peptides presented by H2-Kbα3A2 or H2-Kb , the rank order of the functional avidities matched that of the lifetimes of bimolecular bonds and total bonds (Fig. 5a, b). These plots showed a sharp separation at the border between the positive- and negative-selection ligands with very small differences in their mean bond lifetimes.
- Structural Features of the αβTCR Mechanotransduction Apparatus That Promote pMHC Discrimination:
	- Within any given mammal, there are millions of distinct αβ T cells each with their own unique αβTCR expressed at 20,000–40,000 copies per T lymphocyte.
	- The exquisite specificity and sensitivity of a high avidity αβ T lymphocyte allow it to recognize several copies of a singular peptide displayed among a sea of unrelated (100,000) but similarly sized moieties (~9 residues in length) on a cell.
- Mediation of T-cell activation by actin meshworks (Beemiller and Krummel, 2010):
	- In their initial encounters with antigen-bearing dendritic cells (DCs), T cells also often rapidly couple and uncouple on the order of minutes, rather than dwelling for extended periods of time on single DCs (Gunzer et al. 2000; Mempel et al. 2004). This dynamic coupling allows T cells to quickly sample a large proportion of the total APC membrane pool in search of their cognate antigen. Still, these transient contacts are productive—they induce calcium fluxes and the expression of markers of activated T cells— indicating that TCR signalosome outputs can be initiated in mere minutes and survive the dissolution of contacts, even under the mechanical stress of cytoskeletal remodeling.
- Regulation of {T}-cell receptor signaling by the actin cytoskeleton and poroelastic cytoplasm (Beemiller and Krummel, 2013):
	- As TCR signaling begins, TCRs coalesce into signaling microclusters containing hundreds of TCRs (17). These signaling microclusters require an intact actin cytoskeleton to form and dynamically recruit factors that can scaffold signaling complexes onto the actin cytoskeleton;
	- Using PALM, two groups have analyzed the nanoscale organization of TCRs and how that organization changes in response to agonists (26, 27). TCRs were found to pre-cluster into islands—approximately 50 nm radius probability peaks consisting of 7–20 TCRs (26). Upon stimulation, TCRs islands linked together into microclusters containing hundreds of TCRs. LAT was also shown to reside in nanoclusters independent of stimulation. Like TCRs, LAT clustering was increased on stimulating surfaces. Following stimulation, domains of TCR and LAT clusters were found to concatenate—the domains mixed, but did not fully merge (26). These regions of mixing or overlap were suggested to be ‘hotspots’ of LAT phosphorylation.
	- In vivo, T cells encounter APCs as they constitutively move through an environment presenting various chemokine and adhesive signals. TCR signaling is initiated in brief, serial encounters with agonist bearing dendritic cells (96). During the early phases of antigen responses, T cells establish and break contact with one or more dendritic cells, allowing them to ‘integrate’ the agonist abundance, which controls incorporation of T cells into the immune response (97, 98).
- Mechanical forces amplify TCR mechanotransduction in T cell activation and function (N. Jeffreys et.al, 2023):
	- Although there is currently no technique available to enable TCR–pMHC force measurements in vivo, these TCR–pMHC forces have been directly observed and computed in vitro with traction force microscopy,71 elastomeric micropillar arrays,72,73 and molecular tension force probes.10,74–77 Additional nanoscale force measurements made on TCR–pMHC bonds include atomic force microscopy (AFM),78–80 biomembrane force probes,81,82 and optical tweezers.
	- In these weakly cross-linked polymer networks, viscoelasticity can be modulated independently of the storage modulus (Table I) by combining and varying the following parameters: macromolecular weight of the constituent polymer; the coupling of inert molecules to the constituent polymer as nanoscale plasticizers; weak bond dissociation kinetics; the stoichiometric ratio between weak and covalent bonds; and the net number of bonds.
- Mechanosensing in the immune response (A. Upadhyaya, 2017):
	- Husson et al. developed a force probe to measure forces exerted by the T cell on an antibody-coated microbead [74]. Activation resulted in a pushing response, as the T cell spread on the microbead, followed by a pulling response, accompanied by Ca2+ influx and early signaling. The typical force generated during the pushing phase was ∼20–30 pN. The median loading rate during the pulling phase was ∼2-3 pN/sec and increased linearly with probe stiffness, suggesting a form of mechanosensitivity. However, Ca2+ dependence on stiffness was not measured.
	- Li and Butte used an atomic force microscope (AFM) tip coated with anti-CD3 or pMHC to stimulate primary and Jurkat T cells and measured pushing and pulling forces ∼1nN [75]. Interestingly, they did not find correlations between the total Ca2+ flux and the magnitude of the applied force. but these were temporally correlated. Actin dynamics and myosin contractility were required for force generation.
	- We used PA gels coated with anti-CD3 antibodies to measure traction forces while simultaneously monitoring actin dynamics [19]. We found that cells exerted average traction stresses in the range of 5–10 Pa, peak traction stresses of 10–30 Pa corresponding to ∼1-2nN of total force. These forces were specific to TCR-ligand binding, and both actin dynamics (polymerization and depolymerization) and NMII activity were required for force generation. We have recently shown that microtubule tip dynamics modulate force generation in T cells.
	- Blocking the movement of TCR microclusters from the periphery to the center prolonged pY signaling levels [104], suggesting location-dependence of TCR signaling. Intriguingly, actin dynamics in the vicinity of stalled clusters was altered compared to the regions between barriers [105]. In a complementary approach, altering the mobility of lipids and proteins by modifying the lipid composition of stimulatory bilayers showed that increased diffusivity resulted in higher Ca2+ influx, greater microcluster mobility and enhanced pY signaling as well as altered actin dynamics [106]. It is interesting to note that these two studies suggest opposite effects of mobility on signaling, however the mechanisms behind these differences remain to be explored.
	- T and B cells navigate complex topography in the lymph nodes and thymus with extensive membrane folds on APC surfaces or fibrillar structures on follicular dendritic networks. These structures present regions of high curvature, which might recruit curvature-sensing signaling proteins and actin regulators, thereby modulating cytoskeletal dynamics. The role of topography on immune cell signaling activation is an open question for future studies
- Mechanoimmunology of T-Cell Activation (X. Wu & Z. Ye, 2025):
	- Liu et al. utilised a nanoparticle tension sensor on DNA, revealing that molecular forces exceeding 12 pN were transmitted to the TCR within seconds of binding to a specific pMHC, prior to the initiation of calcium signaling[35]. Goehring et al. detected TCR force using a single-molecule sensor, finding a peak force of approximately 5 pN in supported lipid bilayers, significantly higher than the 2pN.
	- Liu et al. found that when a 10 pN force was applied to an agonist TCR–pMHC complex, the catch bonds formed with the longest lifetimes, producing the strongest TCR signals. Early and rapid accumulation of TCR–pMHC bond lifetimes resulted in strong T cell signaling[41].
	- Mallis et al. explored γδ T cells using bioinformatic analysis, molecular dynamics and single-molecule optical tweezer technology. They found that γδ T cells do not use mechanosensing for ligand recognition [69]. This is because the γδTCR cannot form stable catch bonds in response to mechanical forces and lacks the metastructures required for mechanotransduction.
	- YAP also senses changes in microenvironmental stiffness and modulates T-cell activation and metabolism [129, 130]. Through the fine-tuning of such forcesensitive proteins, T cells achieve precise responses to mechanical stimuli.
	- Upon activation, T cells undergo notable changes in their mechanical properties, including alterations in hardness and tension. These changes include significant modifications in T-cell size and morphology, leading to the formation of soft microvilli and irregular surface folds that optimise the contact area. T cells exhibit highly viscous droplet-like behaviour, characterised by contractile forces at their periphery, that is, cortical tension, akin to surface tension, which shapes the cells into a spherical form.
	- In a study by Waugh et al., single-cell microcapillary aspiration was used to assess changes in the mechanical properties of activated versus unactivated T cells [131]. The study revealed that cell volume increased following activation. While naïve and activated T cells exhibited similar average cortical tensions, activated CD8 T cells showed significantly different cortical tension compared to their naïve counterparts. Cell activation generally leads to increased resistance to deformation and a broader distribution of cellular properties, potentially contributing to promoted antigen capture. High membrane tension plays a pivotal role in inhibiting the formation of short, branched actin filaments while promoting the growth of linear, elongated actin filaments.
	- Thauland et  al. reported that naïve T cells possess a stiffer cytoskeleton than effector T cells, resulting in smaller IS sizes and weaker TCR signaling. Interestingly, tension was found to counteract cytoskeletal production [134]. However, other studies observed increased cellular stiffness with higher levels of T-cell activation. High membrane tension was associated with the assembly of actin filaments and adhesion patches, cell spreading, the formation of membrane ruffles and larger clusters of TCRs, collectively enhancing antigen sensitivity in T cells.
	- During physiological processes, T cells can respond to changes in the stiffness of dendritic cells (DCs), which are a major APC and mature DCs can activate T cells [137, 138]. During DC maturation, increased actin polymerization leads to higher cortical stiffness, which promotes T-cell activation, lowers the threshold dose of TCR ligands required for activation and increases stiffness sensitivity in CD4 T cells compared to CD8 T cells.
	- Piezo 1 impacts T-cell activation and regulates cellular inflammation and migration via integrins. Membrane stretching during IS formation triggers Piezo 1 activation and Ca2+ influx, which activates calpain. Calpain subsequently organizes cortical actin scaffolds, optimizing T-cell activation.
	- Activated Piezo 1 promotes calcium influx, increasing ZAP70 phosphorylation in TCR signaling. This leads to the activation of transcription factors NFAT, NF-κB and activator protein, ultimately increasing the expression of cytokines such as IL-2, TNF-α and IFN-γ [162]. During adhesion and migration, Piezo 1 mediates T-cell responses to mechanical force by regulating LFA1 affinity and influencing T lymphocyte crawling rates. Piezo 1 preferentially binds to integrin α subunits, facilitating T-cell migration from lymph nodes to inflammation sites.
	- Beppler et al. utilised high-resolution dot-matrix light curtains and total internal reflection fluorescence imaging to visualise microvillus scanning during CAR-T cell design modification. Their results demonstrated that microvillus dynamics could be stabilised by adjusting receptor affinity and antigen density, which improved effector function [190]. They demonstrated ultrastable microvillus contact for conventional CARs relative to TCR.
- Biophysical Aspects of T Lymphocyte Activation at the Immune Synapse (C. Hivroz & K. Saitakis, 2017):
	- A laser trap was used to position two beads, one as source of chemokine gradient and the other to measure the forces exerted by the migrating T lymphocytes (in their case, the Jurkat leukemic T cell line). The protrusion forces measured at the leading edge of Jurkat cells migrating in a gradient of SDF-1 were as high as 1000 pN and increased in parallel to the chemoattractant gradient. Moreover, the forces required to stop the migrating cells ranged from 100 to 300 pN.
	- In one study, Hosseini et  al. used atomic force microscopy (AFM) to measure the adhesion forces between a T cell hybridoma and a B cell line used as APC. Results showed that in the presence of antigen, adhesion forces built up with time of conjugate formation, starting from 1 to 2 nN at the beginning of the interaction to 14 nN after 30 min. The adhesion forces were mainly due to lymphocyte function-associated antigen-1 (LFA-1)-mediated adhesion, since the integrin inhibitor BIRT377 almost completely abolished forces in the conjugates.
	- Jurkat cells were put on polyacrylamide gels coated with anti-CD3 antibodies and embedded with fluorescent beads at the top surface. The traction forces exerted by the cells were measured by tracking fluorescent bead displacement. In the presence of antiCD3 and for a substrate stiffness rigidity of 1–2 kPa, traction forces were in the order of 2 nN, whereas forces exerted on substrates coated with a non-activating antibody were below 1 nN.
	- It has been shown that the integrin bonds “remember” the history of the forces they have been submitted to. This phenomenon was called “cyclic mechanical reinforcement,” as the bond strength accumulates over repeated cycles of forces and is maintained after force removal. For instance, fibronectin/α5β1 integrin bonds dissociate within 1 s at a force of 5 pN, while upon cyclic mechanical reinforcement, the bond lifetimes can be extended to 14 s. Similar mechanisms apply to LFA-1/ICAM-1-specific bonds.
	- Plastic and glass display stiffness in the ranges of gigapascal. In contrast, cells in the body generally display stiffness in the range of 50 Pa–40 kPa with primary human T lymphocytes and Jurkat cells being at the soft end of this range with their stiffness ranging from 50 to 90 Pa.
	- Using a singlecell rheometer, we recently showed that different human myeloid APCs have different viscoelastic properties and that their Young’s modulus values vary from 500 Pa for monocytes and DCs to 900 Pa for macrophages. Moreover, inflammatory conditions modified the viscoelastic properties of myeloid cells, which were halved or doubled when cells were treated with a TNFα/ PGE2 cocktail or IFNγ, respectively.
	- The viscoelastic properties of human myeloid cells were dependent on myosin IIA activity and correlated to the F-actin content in each type of cells. These results suggest that the actomyosin cytoskeleton of myeloid cells is responsible for their mechanical properties.
	- It was recently shown that the contractility of fibroblastic reticular cells is regulated upon inflammation by the expression of CLEC-2 on mature dendritic cells. CLEC-2, by interacting with podoplanin expressed on fibroblastic reticular cells, induces the relaxation of these cells that leads to a decrease of the lymph node stiffness that is probably important for its expansion.
	- Strong TCR stimulation can lead to complete arrest of T lymphocyte migration and stable conjugation with an APC, which can last several hours, while when interacting with TCR ligands of low potency or low affinity, T lymphocytes do not completely stop migrating and establish brief dynamic contacts with the APC termed kinapses. TCR signaling strength modifies the actomyosin cytoskeleton of T lymphocytes, which may lead to an alteration of their mechanical properties.
- T-cell mechanobiology: How molecular forces shape immune function (Zubia-Aranburu et.al, 2026):
	- Although the three cell types show comparable calcium signaling upon stimulation, Jurkat cells exhibit a delayed calcium response, reflecting underlying differences in the cytoskeleton. At the IS, the actin network is morphologically distinct: primary T cells show dynamic cortical actin undulations (∼0.1 Hz), whereas Jurkat cells have a stable cortical network. While both cell types feature lamellipodium and lamellum structures, Jurkat cells lack actin foci.
	- These architectural differences translate into different force generation strategies. In primary T cells, filamentous actin (F-actin) flow is driven by myosin II contractility, while Jurkat cells mostly rely on actin nucleation and polymerization. TCR mobility remains robust and is insensitive to the disruption of the two main actin nucleators (formin and Arp2/3) or myosin II, which suggests that TCR mobility can be sustained despite an altered actin architecture, because Jurkat T cells lack negative regulators of TCR signaling like SHIP-1 or PTEN (Colin-York et al., 2019b).
- T-cell activation is modulated by the 3D mechanical microenvironment (F. S. Majedi et.al., 2020):
	- We have previously shown that naive T cells are mechanically stiffer than activated effector T cells. This difference in stiffness allows the more pliable effector T cells to form larger IS with APCs upon initial triggering, increasing the number of receptor-ligand interactions and enhancing activation. Thus, the T-cell cytoskeleton acts as a layer of regulation, allowing effector cells to sensitively respond to APCs.
	- While stiffness and ligand density can be modulated independently of polymer content with some synthetic polymers, the direct relationship between crosslinker density and mesh size has made it difficult at best to relate cell behavior to pure stiffness. Fortunately, in the case of the biodegradable polymer alginate gelation is induced by calcium ions. Due to the formation of G-blocks that provide pockets for calcium entrapment, the stiffness of the gel can be altered by varying the concentration of calcium ions without altering the ligand density or pore size.
	- When measured by AFM, micropillars, or traction force microscopy, the subsequent pulling forces generated by single T cells range from 100 pN to 1 nN. On the single-TCR level, these forces were found by DNA tension probes to range from 10 to 20 pN.
- Engineering an Artificial T‐Cell Stimulating Matrix for Immunotherapy (J.W. Hickey et.al, 2019):
	- We chose HA as an ECM mimic because it can be easily modified through tunable chemistry—which enables the addition of adhesive ligands, conjugation of drugs or growth factors, and control of the elastic modulus and porosity of the hydrogel.
	- Secondary lymphoid tissue is a soft tissue and the stiffness has been reported to be between 0.1 to 2 kPa.
- Different TCR-induced T lymphocyte responses are potentiated by stiffness with variable sensitivity (M. Saitakis et.al, 2017):
	- Addition of TSST1 induced a dose-dependent increase of cytokine production that was higher when the HeLa-CIITA APCs were plated on the stiffer 28 kPa gel than on the softer 1.5 kPa gel.
	- We tried to increase the rigidity of HeLa-CIITA APCs by growing them to confluence on glass slides (rigidity in the order of GPa). In this condition, HeLa-CIITA did not show any increase in cell area as compared to cells grown on 28 kPa. This might reflect the fact that cell rigidity had already reached saturating conditions, as shown for fibroblast and MSC rigidity on substrate stiffness values of 20 kPa and above. The lack of increase in HeLa-CIITA cell area on glass was accompanied in co-cultures by a lack of increase in TCR-induced cytokine production by T lymphoblasts.
	- Metastatic cancer cells and leukemic cells were reported to be generally very soft (Rosenbluth et al., 2006; Lam et al., 2007; Bufi et al., 2015), in the range of 0.05 to 0.2 kPa, which could be one more mechanism of immune evasion.
- Effect of binary mechanical environment on T-cell function (J.J. Pandit et.al., 2025):
	- Importantly, while the natural environment of T cells contains predominantly cells and tissues whose stiffness is up to ~100 kPa, T cells are able to sense the stiffness much above this range, and modify their immune response according to the variations in the stiffness beyond 100 kPa.
- Microdevice for confinement of T-cells on functionalized bio-interfaces (C. Trenzinger et.al., 2025):
	- Leukocytes have been shown to discriminate pore size using their nucleus as a mechanical gauge, which helps them to determine their migration path of least resistance. Confinement-induced responses allow immune cells therefore to adapt to changing environments and to migrate efficiently within tissues.
- Nanoconfinement of microvilli alters gene expression and boosts T cell activation (M. Aramesh et.al., 2021):
	- Using lattice light-sheet microscopy and real-time tracing of dynamic microvilli on two-dimensional (2D) surfaces, the lifetime of the microvilli protrusions is estimated to be roughly 1 min.
- Cytoskeletal forces during signaling activation in {Jurkat} {T}-cells (Hui et.al., 2014)
	- The effective internal stress generated in the viscoelastic actin network can be estimated from the material parameters of the cell (Betz et al., 2011). Independent measures of Jurkat cell stiffness suggest that these are soft (Young’s modulus, ∼50–100 Pa [pN/μm2]; Rosenbluth et al., 2006), which likely limits the peak internal stresses to 100 Pa at best.
	- Typically, cells were completely spread before 15 min, as shown in the EGFP-actin images of a typical cell spreading on a gel of stiffness 1.7 kPa (which approximates the stiffness of APCs; Rosenbluth et al., 2006).
	- The average traction stresses exerted by cells were in the range of 5–10 Pa, whereas the peak traction stresses exerted were in the range of 10–30 Pa, in the same range as stresses exerted by neuronal growth cones (Betz et al., 2011; Koch et al., 2012). By contrast, rapidly migrating keratocytes and strongly adherent fibroblasts are known to exert traction stresses in the range of 100 Pa to several kilopascals (Lee et al., 1994; Dembo and Wang, 1999).
	- The total force exerted by cells (average force between 14 and 15 min of spreading initiation on gels of stiffness 1–2 kPa) showed considerable variation, with a median value of 2 nN (Figure 1e). Based on the observed stiffness of Jurkat cells (Young’s modulus E ≈ 50–100 Pa; Rosenbluth et al., 2006), the expected value of maximum force is F ≈ E × area ≈ 2–5 nN. These observed forces are largely a direct consequence of TCR–ligand binding leading to T-cell activation.
	- The median value of retrograde flow of actin ( for cells spreading on gels of stiffness 1–2 kPa) was measured to be 3 μm/min, which was consistent with other soft cells such as hippocampal neurons (Koch et al., 2012).
- - Mechanical regulation of T-cell functions:
	- The active transport process driven by the actin retrograde flow can produce drag forces on membrane receptors engaged with ligands on the APC, as most of them anchor to actin cytoskeleton through adapter molecules. For example, LFA-1 anchors to cytoskeleton via talin, and the TCR/CD3 complex via molecular complexes that involve coreceptor CD4/CD8, Lck, Zap70, and others;
	- Segregation of small and large molecules into cSMAC and pSMAC (central and peripheral supramolecular activation cluster), respectively, can produce membrane bending on both the T-cell and APC surfaces (47–49), which may result in pulling force on short molecules, such as the TCR/CD3 complex;
	- Cyclic protrusion and contraction of distal-SMAC (dSMAC, outside of pSMAC) may exert force on and reinforce receptor–ligand interactions, which may provide a biophysical mechanism for the T cell to regulate IS and kinapse formation and to sense the mechanical properties of the APC.
	- Mechanical force may act on the TCR– pMHC bonds when the T-cell membrane moves relative to the APC membrane as a result of cell motility (Fig. 1B), or in the case of stable T-cell–APC conjugates as TCR microclusters form and stream along the actin cytoskeleton to the IS cSMAC (Fig. 1C). Recently published data suggest that the TCR can mediate sensing of mechanical force (44, 61) and substrate rigidity (8, 9) via engaged pMHCs or antibodies;
	- Mossman et al. (148) found that blocking the free transport of TCR microclusters in planar bilayers with chrome barriers enhanced the levels of early TCR-associated phosphorylated tyrosine and elevated cytoplasmic Ca2+. These data suggest that chrome barriers may introduce mechanical effect on TCR triggering;
	- During IS formation, a T cell generates cyclic protrusion–contraction in the periphery of the IS. This cyclic contraction may allow the T cell and the APC to exert force on TCR–pMHC bonds to mediate TCR triggering (43). Similarly, actively transporting TCR microcluster from the dSMAC and pSMAC to cSMAC by actin retrograde flow may also induce dragging force on TCR–pMHC bonds, thereby modulating TCR triggering;
	- Disrupting actin cytoskeleton by pharmacological agents abolished TCR downstream signaling;
	- Reinherz and colleagues (44) observed that tangential, but not normal, force applied to the TCR via an antibody or pMHC can induce Ca2+ signals. These authors proposed that force might induce conformational changes in the b constant domain F–G loop that might propagate to other parts of the TCR/CD3 complex to initiate T-cell signaling;
	- Li et al. (61) also showed that both a mild shear force from micropipette suction and pulling the TCR/CD3 complex with an elongated CD3 ligand could induce Ca2+. As this elongated CD3 ligand could not induce T-cell activation in the absence of externally applied forces, their data imply that force may enhance segregation of large-size phosphatases (e.g. CD45) from the small-sized TCR to shift their local balance with kinases (e.g. Lck) in favor of phosphorylation.
	- Lim et al. (153) found that adhesion strengths (as assessed by AFM pulling) between a T cell and a DC loaded with different pMHCs correlate with T-cell responsiveness, suggesting that mechanically stable DC–T cell contacts are crucial for driving T-cell activation;
	- Lam and coworkers (8) showed that T cells can respond to changing substrate rigidity in a TCR-dependent manner, supporting the mechanosensing ability of the TCR.
	- Both the smFRET and mechanical studies found much faster 2D TCR– pMHC off-rates than their three-dimensional (3D) counterparts measured using soluble protein constructs by SPR;
	- Huppa et al. (154) found that disrupting the actin polymers decreased the 2D off-rates of TCR–pMHC dissociation, suggesting that cytoskeleton dynamics destabilizes this interaction;
	- Theoretical studies suggest that segregation of long surface molecules (e.g. CD45) away from TCRs may introduce time-dependent tension stretching the TCR–pMHC bonds leading to an increase in the 2D off-rates (49) and that force may amplify the dynamic range of antigen discrimination.
	










